apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "inception-of-things"
  namespace: argocd
spec:
  description: "part 3"
  sourceRepos:
    - "http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/*"
  destinations:
    - namespace: dev
      server: "https://kubernetes.default.svc"
