# project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "inception-of-things"
  namespace: argocd
spec:
  description: "part 3"
  sourceRepos:
    - "https://github.com/ltouret/*"
  destinations:
    - namespace: dev
      server: "https://kubernetes.default.svc"
