# vi: set ft=ruby :

# Use vagrant v2
Vagrant.configure("2") do |config|
  # Use alpine 3.16
  config.vm.box = "generic/alpine316"
  # limit resources access
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
  # Setup shared folder between host and VMs
  config.vm.synced_folder "./shared", "/vagrant"

  # This is triggered before both VMs are started which is useless
  # Copy ssh key before starting
  config.trigger.before :up do |trigger|
    trigger.run = { inline: <<-SHELL
      bash -c "
        if [ ! -f ~/.ssh/id_rsa ]
        then
          ssh-keyken -f ~/.ssh/id_rsa -N ''
        fi
        cp ~/.ssh/id_rsa.pub ./shared
      "
      SHELL
    }
  end

  # Create the ltouretS VM
  config.vm.define "ltouretS" do |master|
    master.vm.hostname = "ltouretS"
    # You may need to add a /etc/vbox/networks.conf file containing
    # '* 0.0.0.0/0 ::/0' on your host system for this line to work properly
    master.vm.network :private_network, ip: "192.168.42.110"
    # Run at VM creation the K3s installation script in controller mode
    master.vm.provision "shell", privileged: true, path: "install_k3s.sh", args: ["controller"]
  end

  # Create the ltouretSW VM
  config.vm.define "ltouretSW" do |worker|
    worker.vm.hostname = "ltouretSW"
    # You may need to add a /etc/vbox/networks.conf file containing
    # '* 0.0.0.0/0 ::/0' on your host system for this line to work properly
    worker.vm.network :private_network, ip: "192.168.42.111"
    # Run at VM creation the K3s installation script in agent mode
    worker.vm.provision "shell", privileged: true, path: "install_k3s.sh", args: ["agent", "192.168.42.110"]
  end
end
