# vi: set ft=ruby :
#
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Vagrantfile                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: frdescam <marvin@42.fr                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/21 19:41:41 by frdescam          #+#    #+#              #
#    Updated: 2022/10/21 19:44:08 by frdescam         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CONTROLLER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

CONTROLLER_HOSTNAME = "ltouretS"
WORKER_HOSTNAME = "ltouretSW"

# Use vagrant v2
Vagrant.configure("2") do |config|
  # Use alpine 3.18
  config.vm.box = "generic/alpine318"
  # limit resources access
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
  # Setup shared folder between host and VMs
  config.vm.synced_folder "./shared", "/vagrant"

  # We insert our own ssh key so no need for theirs
  config.ssh.insert_key = false

  # Create the server VM
  config.vm.define CONTROLLER_HOSTNAME do |master|
    master.vm.hostname = CONTROLLER_HOSTNAME
    master.vm.network :private_network, ip: CONTROLLER_IP
    master.vm.network :forwarded_port, guest: 22, host: 2022, id: "ssh"
    # Run at VM creation the K3s installation script in controller mode
    master.vm.provision "shell", privileged: true, path: "install_k3s.sh", args: ["controller", CONTROLLER_IP]
    master.vm.provision "shell", privileged: false, path: "install_ssh_pubkey.sh"

    # Copy ssh key before starting VMs
    master.trigger.before :up do |trigger|
      trigger.run = { inline: <<-SHELL
        bash -c "
          if [ ! -f ~/.ssh/id_ed25519 ]
          then
            ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''
          fi
          cp ~/.ssh/id_ed25519.pub ./shared
        "
        SHELL
      }
    end
  end

  # Create the worker VM
  config.vm.define WORKER_HOSTNAME do |worker|
    worker.vm.hostname = WORKER_HOSTNAME
    worker.vm.network :private_network, ip: WORKER_IP
    worker.vm.network :forwarded_port, guest: 22, host: 2023, id: "ssh"
    # Run at VM creation the K3s installation script in agent mode
    worker.vm.provision "shell", privileged: true, path: "install_k3s.sh", args: ["agent", WORKER_IP, CONTROLLER_IP]
    worker.vm.provision "shell", privileged: false, path: "install_ssh_pubkey.sh"
  end
end
