# vi: set ft=ruby :
#
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Vagrantfile                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: frdescam <marvin@42.fr                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/21 19:41:41 by frdescam          #+#    #+#              #
#    Updated: 2022/10/21 19:44:08 by frdescam         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

SERVER_HOSTNAME = "ltouretS"
WORKER_HOSTNAME = "ltouretSW"

# Use vagrant v2
Vagrant.configure("2") do |config|
  # Use alpine 3.16
  config.vm.box = "generic/alpine316"
  # limit resources access
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
  # Setup shared folder between host and VMs
  config.vm.synced_folder "./shared", "/vagrant"

  # Create the server VM
  config.vm.define SERVER_HOSTNAME do |master|
    master.vm.hostname = SERVER_HOSTNAME
    master.vm.network :private_network, ip: SERVER_IP
    # Run at VM creation the K3s installation script in controller mode
    master.vm.provision "shell", privileged: true, path: "install_k3s.sh", args: ["controller"]

    # Copy ssh key before starting VMs
    master.trigger.before :up do |trigger|
      trigger.run = { inline: <<-SHELL
        bash -c "
          if [ ! -f ~/.ssh/id_rsa ]
          then
            ssh-keygen -f ~/.ssh/id_rsa -N ''
          fi
          cp ~/.ssh/id_rsa.pub ./shared
        "
        SHELL
      }
    end
  end

  # Create the worker VM
  config.vm.define WORKER_HOSTNAME do |worker|
    worker.vm.hostname = WORKER_HOSTNAME
    worker.vm.network :private_network, ip: WORKER_IP
    # Run at VM creation the K3s installation script in agent mode
    worker.vm.provision "shell", privileged: true, path: "install_k3s.sh", args: ["agent", SERVER_IP]
  end
end
